config/routes.rb
Rails.application.routes.draw do
	resources :articles
	#devise_for :users
	devise_for:users

	devise_scope :user do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end

=begin
		get '/articles' 				#index
		post '/aticles' 				#create
		delete '/articles/:id' 				#delete
		get '/aticles/:id' 				#show
		get '/articles/new' 			#new
		get '/articles/:id/edit' 		#edit
		patch '/articles/:id' 			#update
		put '/articles/:id' 			#update
=end
root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :name, presence: { message: "El Nombre del Producto no puede quedar vacio" }
	validates :brand, presence: { message: "La Marca del Producto no puede quedar vacia" }
  validates :price, presence: { message: "El Producto debe tener un precio" }
  validates :quantity, presence: { message: "El Producto debe tener una cantidad" } 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	#get /articles
	def index
		@articles = Article.all
	end

	#get /articles/id
	def show
		@articles = Article.find(params[:id])
	end

	#get /articles/new
	def new
		@articles = Article.new
	end

	#post /articles
	def create

		@articles = Article.new(name: params[:article][:name],
								brand: params[:article][:brand],
								price: params[:article][:price],
								quantity: params[:article][:quantity])

		if @articles.valid?
			@articles.save
			redirect_to @articles, :flash => { :success => "Message" }
		else
			render :new
		end

	end

	#PUT /articles/:
	def edit
		@articles = Article.find(params[:id])
	end

	#put /articles:id
	def update
		# #update
		@articles = Article.find(params[:id])
		if @articles.update(name: params[:article][:name],
											 brand: params[:article][:brand],
											 price: params[:article][:price],
											 quantity: params[:article][:quantity])
			redirect_to @articles
		end
	end

	#Destroy
	def destroy
        @articles = Article.find(params[:id])
        @articles.destroy
        redirect_to "/articles"
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<style type="text/css">

	.error {
		background-color: #ff000091;
		padding: 1em;
		text-align: center;
		color: #fff;
		border-radius: 5px;
		box-shadow: 5px 4px 15px #d8d8d8;
		display: block;
	}

	input[type=submit] {
	  width: 100%;
	  background-color:#2364FE;
	  color: white;
	  padding: 14px 20px;
	  margin: 8px 0;
	  border: none;
	  border-radius: 4px;
	}
</style>

<div class="container">
		<div>
			<% if @articles.errors.any? %>
			<script type="text/javascript">
				function hideError (e) {
					document.getElementById('error').style.display = "none"
				}
			</script>
			<p  id="error"class="error" onclick="hideError();">Error de Guardado</p>
		 <% end %>
		</div>

	<%=form_with model: @articles do |f| %>
	<div class="form-group">
				<%=label(f, "Nombre del Producto", {:class => "col-md-4 control-label"})%>
				 <div class="col-md-6">
					 <%= f.text_field :name, {:class => "form-control", required: true} %>
				 </div>
	</div>
	<div class="form-group">
				<%=label(f, "Marca del Producto", :class => "col-md-4 control-label")%>
				 <div class="col-md-6">
					 <%= f.select(:brand , raw('<option value="Maxell">Maxell</option>
					 														<option value="Esenses">Esenses</option>
																			<option value="Genius">Genius</option>'), {required: true}, {:class => "form-control"} ) %>
				 </div>
	</div>
	<div class="form-group">
				<%=label(f, "Precio del Producto", {:class => "col-md-4 control-label"})%>
				 <div class="col-md-6">
					 <%= f.number_field :price, {:class => "form-control" , min: "0", required: true} %>
				 </div>
	</div>
	<div class="form-group">
				<%=label(f, "Cantidad del Producto", {:class => "col-md-4 control-label"})%>
				 <div class="col-md-6">
					 <%= f.number_field :quantity, {:class => "form-control" , min: "0", required: true} %>
				 </div>
	</div>
	<div class="form-group">
				 <div class="col-md-6">
					 <%= f.submit value:"Guardar" %>
				 </div>
	</div>
</div>

<%end%>

app/views/articles/edit.html.erb
  <div class="container">
    <h1>Editar Producto</h1>
  </div>
  <%= render "form" %>

app/views/articles/index.html.erb
<style type="text/css">
	#crear_boton{
		margin-bottom: 20px;
	}

	#btn{

    position: relative;
    left: 70px;
    bottom: 37px;
	}
</style>
<div class="container" id="crear_boton">
	<%= link_to "Crear", new_article_path, class:"btn btn-outline-primary btn-lg"%>
</div>
<div class="container">
	<div class="row">
		<%@articles.each do |article| %>
		  <div class="col-sm-4">
		    <div class="card">
		      <div class="card-body">
		        <h5 class="card-title"><%= link_to article.name , article%></h5>
		        <p class="card-text"><%= article.brand%></p>
							<p>	Precio $<%= article.price%></p>
							<p> Unidades <%= article.quantity%></p>
		       		<%= link_to "Editar", edit_article_path(article), class:"btn btn-outline-primary"%>
							<%= button_to "Eliminar", article, method: :delete, class:"btn btn-outline-danger", id: "btn" %>
		      </div>
		    </div>
		  </div>
		<br>
		<%end%>
	</div>
</div>

app/views/articles/new.html.erb
<div class="container">
	<h1>Crear Producto</h1>
</div>
<%= render "form" %>

app/views/articles/show.html.erb
<h1>
	<%= @articles.name%>
</h1>
<div>
	<%=@articles.brand%>
	<br>
	<p>	Precio $<%= @articles.price%></p>
	<p> Unidades <%=  @articles.quantity%></p>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <title>Prueba Ruby on Rails</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

<div class="">
  <p class="notice" hidden="true"><%= notice %></p>
  <p class="alert" hidden="true"><%= alert %></p>
</div>
    <%= render "partials/navigation" %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<% unless flash.empty? %>
   <script type="text/javascript">
      <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
     toastr['<%= type %>']('<%= f[1] %>');
   <% end %>
   </script>
<% end %>

<style type="text/css">

  html,body{
    font-family: 'Roboto', sans-serif;
  }

  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    text-align: center;
  }

  li {
      display: inline;
      padding: 12px 50px;
    }
</style>
<header>
  <ul class="nav justify-content-center">
      <li class="nav-item">
        <%= link_to "Inicio", articles_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Subir Productos", articles_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Pedir Productos", articles_path, class:"nav-link"%>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to('Cerrar Session',  destroy_user_session_path, :method => 'delete', class:"nav-link")%>
        </li>
      <%else%>
        <li>
          <%= link_to('Iniciar Sesion',  new_user_session_path, class:"nav-link")%>
        </li>
        <li>
          <%= link_to('Crear Cuenta',  new_user_registration_path, class:"nav-link")%>
        </li>
      <%end%>
  </ul>
  <br>
</header>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>